# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b83faef211551afa7b5c79580162057a"
name = "test-app"
# 加上端口号（如果你 Remix 跑在 3000）
application_url = "http://xianyili.top:3000" 
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
scopes = "write_products"

[auth]
redirect_urls = [ 
    "http://xianyili.top:3000/auth/callback",
    "http://xianyili.top:3000/auth/shopify/callback",
    "http://xianyili.top:3000/api/auth/callback"
]
