# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b83faef211551afa7b5c79580162057a"
name = "test-app"
# 加上端口号（如果你 Remix 跑在 3000）
application_url = "https://xianyili.top" 
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
scopes = "write_products"

[auth]
redirect_urls = [ 
    "https://xianyili.top/auth/callback",
    "https://xianyili.top/auth/shopify/callback",
    "https://xianyili.top/api/auth/callback"
]