# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b83faef211551afa7b5c79580162057a"
name = "test-app"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
